"""empty message

Revision ID: ed026f663723
Revises: defd5425aa41
Create Date: 2023-03-06 23:25:37.626911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed026f663723'
down_revision = 'defd5425aa41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alert')
    with op.batch_alter_table('favorite_equipment_association', schema=None) as batch_op:
        batch_op.drop_constraint('favorite_equipment_association_equipment_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('favorite_equipment_association_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'equipment', ['equipment_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('favorite_location_association', schema=None) as batch_op:
        batch_op.drop_constraint('favorite_location_association_location_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('favorite_location_association_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'location', ['location_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_location_association', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorite_location_association_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key('favorite_location_association_location_id_fkey', 'location', ['location_id'], ['id'])

    with op.batch_alter_table('favorite_equipment_association', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorite_equipment_association_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key('favorite_equipment_association_equipment_id_fkey', 'equipment', ['equipment_id'], ['id'])

    op.create_table('alert',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('type', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('location_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], name='alert_location_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='alert_pkey')
    )
    # ### end Alembic commands ###
