export const Diving = [
    "Wet Suit",
    "Oxygen Tanks",
    "Oxygen Mask",
    "Regulator",
    "Flippers",
    "Gloves",
    "Nylon Water Shoes",
    "Weight Belt",
    "Waterproof Watch",
    "Snorkel",
    "Swim Attire",
    "Goggles",
    "Water Sack",
    "Spear Gun",
    "Rope",
    "Knife",
    "Diving Flag",
]